project:
  type: website
  output-dir: docs

website:
  title: "Cute puppy website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Res

format:
  html:
    theme:
      - cerulean
    css: styles.css
    toc: true



